# Generated by Django 4.1.4 on 2022-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_futbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_enter', models.CharField(max_length=20)),
            ],
        ),
    ]
